### ISSUE TITLE
gitlab runner does not start

### ISSUE THREAD

**Issue by Hubbitus** [recteurlp/gitlab-ci-multi-runner-fedora#1]
```
# docker run --name gitlab-runner-fedora -d --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /srv/gitlab-runner/config:/etc/gitlab-runner:Z \
    -v /root/.docker/config.json:/root/.docker/config.json \
        gitlab-runner-fedora

# docker logs gitlab-runner-fedora

WARNING: Running in user-mode.                     
WARNING: The user-mode requires you to manually start builds processing: 
WARNING: $ gitlab-runner run                       
WARNING: Use sudo for system-mode:                 
WARNING: $ sudo gitlab-runner...                   
                                                   
Please enter the gitlab-ci coordinator URL (e.g. https://gitlab.com/):
panic: EOF [recovered]
        panic: EOF
goroutine 1 [running]:
panic(0x13e3640, 0xc420010130)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main.func1()
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/main.go:32 +0x7f
panic(0x13e3640, 0xc420010130)
        /usr/local/go/src/runtime/panic.go:458 +0x243
gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands.(*RegisterCommand).askOnce(0xc420166180, 0x15fbb3a, 0x46, 0xc4204e96a0, 0x0, 0x40d6a4)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands/register.go:44 +0x1b6
gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands.(*RegisterCommand).ask(0xc420166180, 0x15b4833, 0x3, 0x15fbb3a, 0x46, 0x0, 0x0, 0x0, 0xc420195aa0, 0x0)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands/register.go:74 +0x103
gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands.(*RegisterCommand).askRunner(0xc420166180)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands/register.go:132 +0x9d
gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands.(*RegisterCommand).Execute(0xc420166180, 0xc42025a4b0)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/commands/register.go:217 +0xb1
gitlab.com/gitlab-org/gitlab-ci-multi-runner/common.(Commander).Execute-fm(0xc42025a4b0)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/common/command.go:24 +0x39
gitlab.com/gitlab-org/gitlab-ci-multi-runner/vendor/github.com/codegangsta/cli.Command.Run(0x15ba1ab, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15cb890, 0x15, 0x0, ...)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/vendor/github.com/codegangsta/cli/command.go:127 +0x79a
gitlab.com/gitlab-org/gitlab-ci-multi-runner/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200a4500, 0xc42000a180, 0x4, 0x4, 0x0, 0x0)
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/vendor/github.com/codegangsta/cli/app.go:159 +0x705
main.main()
        /go/src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/main.go:58 +0x24f
```

**Comment by recteurlp** [comment]
Hi,

To register your runner you have to set the correct environment variables [(QuickStart)](https://github.com/recteurlp/gitlab-ci-multi-runner-fedora#quickstart) or init your container in interactive mode the first time :

``` bash
docker run --name gitlab-runner-fedora -it --rm \
  recteurlp/gitlab-ci-multi-runner-fedora:1.7.1
```

**Comment by Hubbitus** [comment]
as you can see it does not run, so I cant use docker exec on that container!

**Comment by recteurlp** [comment]
With no more feedback from your side i close this issue.
Follow the QuickStart.
